### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by FM33** [pums974/srtsync#1]
Thanks for this very attractive program. I'll try it as soon as I can install it !
```
$ sudo pip install srtsync
The directory '/home/fabien/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/fabien/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting srtsync
  Downloading https://files.pythonhosted.org/packages/1d/08/1d74a9915b585bbaa772fcdcca94693d071e80ce5104dd802cb6c28d1574/srtsync-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d6Ptko/srtsync/setup.py", line 6, in <module>
        import srtsync
      File "srtsync/__init__.py", line 9, in <module>
        from srtsync.tools import sync
      File "srtsync/tools.py", line 90
        print(f"stretching {s:.2f} {1/s:.2f} {stretch:.2f}")
                                                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d6Ptko/srtsync/
```

**Comment by cryzed** [comment]
You are most likely using Python 2 or an outdated version of Python 3. Do not install packages using `$ sudo pip install`; Use a virtual environment or create a package for your operating system instead.

**Comment by tigre-bleu** [comment]
Installed with pip, there is a syntax error:
```
Traceback (most recent call last):
  File "/usr/local/bin/srtsync", line 7, in <module>
    from srtsync.main import main
  File "/usr/local/lib/python3.5/dist-packages/srtsync/__init__.py", line 9, in <module>
    from srtsync.tools import sync
  File "/usr/local/lib/python3.5/dist-packages/srtsync/tools.py", line 90
    print(f"stretching {s:.2f} {1/s:.2f} {stretch:.2f}")
                                                      ^
SyntaxError: invalid syntax
```
Python version is 3.5.3, installed alongside python 2.7.13 which is the default "python" executable.

**Comment by pums974** [comment]
Hi, the minimum python version is python 3.6 (f-string) this is why you have the syntax error.

I will make this clearer.
